version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=sudo
      - RABBITMQ_DEFAULT_PASS=von
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: none    
  consumer:
    container_name: consumer
    build:
      context: ./consumer/
    restart: on-failure:5
    depends_on: 
      - rabbitmq
    ports:
      - 8080:8080
  producer:
    container_name: producer
    build:
      context: ./producer/
    restart: on-failure:15
    depends_on: 
      - rabbitmq
    ports:
      - 8081:8081